language: node_js

node_js: "8"

install: npm install

cache: npm

before_deploy: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "build"
  on:
    branch: master
